name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v3.1.0

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v3.1.0

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v3.1.0
    with:
      args: --all-projects
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-names:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.sha.outputs.SHORT_SHA }}
      pretty_branch_name: ${{ steps.branch.outputs.NAME }}
      matrix: ${{ steps.json.outputs.MATRIX }}
    steps:
      - uses: actions/checkout@v3
      - name: Set short sha output
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short=11 HEAD)" >> $GITHUB_OUTPUT
      - name: Set archive name output
        id: branch
        run: |
          export PRETTY_BRANCH_NAME=$(tr '/' '-' <<< ${{ github.ref_name }})
          echo "NAME=${PRETTY_BRANCH_NAME}" >> $GITHUB_OUTPUT
      - name: Read in lambdas names from JSON
        id: json
        run: |
          echo "MATRIX=$(jq -c . < ./lambdas.json)" >> $GITHUB_OUTPUT

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v3.1.0
    needs: [ build-names ]
    with:
      upload-artifact: true
      build-command: npm run build:prod

  upload-s3:
    if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/') || startsWith(github.ref, 'refs/heads/master')
    uses: dvsa/.github/.github/workflows/upload-to-s3.yaml@v3.1.0
    needs: [ lint, test, build, build-names ]
    strategy:
      matrix:
        lambdaName: ${{ fromJSON(needs.build-names.outputs.matrix).lambdas }}
    with:
      environment: nonprod
      short-commit: ${{ needs.build-names.outputs.short_sha }}
      artifact: ${{ matrix.lambdaName }}.zip
      bucket-key: payments/${{ matrix.lambdaName }}/${{ needs.build-names.outputs.pretty_branch_name }}.zip
      optional-tags: lifecycle_subject=${{ startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/') }}
    permissions:
      id-token: write
    secrets:
      AWS_ROLE_TO_ASSUME_ARN: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
      AWS_ACCOUNT: ${{ secrets.RSP_AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.RSP_AWS_REGION }}
      BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

  update-lambda-code:
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    uses: dvsa/.github/.github/workflows/update-lambda-function.yaml@v3.1.0
    needs: [ build-names, build, upload-s3 ]
    strategy:
      matrix:
        lambdaName: ${{ fromJSON(needs.build-names.outputs.matrix).lambdas }}
    with:
      environment: nonprod
      lambda-function-name: rsp-nonprod-apis-payments-${{ matrix.lambdaName }}
      bucket-key: payments/${{ matrix.lambdaName }}/${{ needs.build-names.outputs.pretty_branch_name }}.zip
    permissions:
      id-token: write
    secrets:
      AWS_ROLE_TO_ASSUME_ARN: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
      AWS_ACCOUNT: ${{ secrets.RSP_AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.RSP_AWS_REGION }}
      BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
